g-mero/esday

- test/getset.test.ts
Add more tests for the  get and set functions.
> Add tests for get and set functions

- package.json
To prepare for activating github actions for validating incoming pushes this project should contain scripts for linting.
> Add scripts for linting to package.json

- src/core/constant.ts
- test/startOf.test.ts
Add more tests for startof and endOf functions.
Changed definition of units in constant.ts to make these values usable as units.
> Add tests for startof and endOf functions

- package.json
- src/common/constant.ts
- src/common/is.ts
- src/common/str-utils.ts
- src/core/EsDay.ts
- src/core/Impl/format.ts
- src/core/factory.ts
- src/core/parseDate.ts
- src/plugins/customParseFormat/index.ts
- src/plugins/locale/index.ts
- src/plugins/utc/index.ts
- src/types/core.ts
- test/format.test.ts
- test/plugins/utc.test.ts
- implement utc plugin
- some compatibility fixes
> add utc plugin

- src/common/constant.ts
- src/common/index.ts
Refactor constant.ts to export all constants as default. Solves issue #22 point 4.
> Refactor constant.ts to export all constants as default

- src/locales/de-at.ts
- src/locales/de.ts
- src/locales/en-gb.ts
- src/locales/en-us.ts
- src/locales/en.ts
- src/locales/es.ts
- src/locales/fr.ts
- src/locales/it.ts
- src/locales/ja.ts
- src/locales/nl.ts
- src/locales/rn.ts
- src/locales/uk.ts
- src/locales/zh-cn.ts
- src/locales/zh.ts
- src/plugins/locale/index.ts
- src/plugins/locale/types.ts
- test/locales/de-at.test.ts
- test/locales/de.test.ts
- test/locales/en-gb.test.ts
- test/locales/en-us.test.ts
- test/locales/en.test.ts
- test/locales/es.test.ts
- test/locales/fr.test.ts
- test/locales/it.test.ts
- test/locales/ja.test.ts
- test/locales/nl.test.ts
- test/locales/rn.test.ts
- test/locales/uk.test.ts
- test/locales/zh-cn.test.ts
- test/locales/zh.test.ts
Add more locales to get a better test coverage.
Update locale type definitions to fix findings from tests.
> Add more locales and update locale type definitions - 2nd try

- src/plugins/isBetween/index.ts
- test/plugins/isBetween.test.ts
Basicly same as [Dayjs](https://github.com/iamkun/dayjs/blob/dev/src/plugin/isBetween/index.js)
> feat: Add plugin `isBetween`

- README.md
- src/core/EsDay.ts
- src/core/Impl/format.ts
- src/plugins/utc/index.ts
- test/format.test.ts
- test/plugins/utc.test.ts
Add more tests for plugin utc and fix findings
> Add more tests for plugin utc and fix findings

- src/common/is.ts
- src/plugins/index.ts
- src/plugins/isLeapYear/index.ts
- src/plugins/isSameOrAfter/index.ts
- src/plugins/isSameOrBefore/index.ts
- src/plugins/minMax/index.ts
- src/plugins/toArray/index.ts
- src/plugins/toObject/index.ts
- test/plugins/isLeapYear.test.ts
- test/plugins/isSameOrAfter.test.ts
- test/plugins/isSameOrBefore.test.ts
- test/plugins/minMax.test.ts
- test/plugins/toArray.test.ts
- test/plugins/toObject.test.ts
- isSameOrAfter
- isSameOrBefore
- toArray
- toObject
- isLeapYear
> feat: add more plugins

- docs/index.md
- docs/locales/locales.md
- docs/plugins/locale.md
- src/plugins/locale/index.ts
Add documentation pages for the plugin locale and for locales defined so far.
> Docs: add documentation for plugin locale and locales

- biome.json
- scripts/skipCI.cjs
- src/common/is.ts
- src/core/factory.ts
- src/plugins/advancedParse/index.ts
- src/plugins/advancedParse/types.ts
- src/plugins/locale/index.ts
- src/plugins/utc/index.ts
- src/types/index.ts
- test/plugins/locale.test.ts
- test/plugins/utc.test.ts
- test/util.ts
Biome creates some warnings - fixed them
> Chore: fix warnings created by biome and update ignore list in biome settings

- .vscode/settings.json
- docs/plugins/locale.md
- scripts/skipCI.cjs
- src/common/esday-inst.ts
- src/core/EsDay.ts
- src/core/Impl/add.ts
- src/core/Impl/startOf.ts
- src/plugins/advancedParse/index.ts
- src/plugins/locale/index.ts
- src/plugins/utc/index.ts
- test/plugins/locale.test.ts
- test/plugins/weekOfYear.test.ts
There were still some eslint fragments - removed them.
> Refactor: remove eslint fragments

- docs/index.md
- docs/plugins/quarterOfYear.md
- src/plugins/index.ts
- src/plugins/quarterOfYear/index.ts
- test/plugins/quarterOfYear.test.ts
implemented plugin QuarterOfYear
> Feat: add plugin QuarterOfYear

- src/core/EsDay.ts
- src/core/Impl/diff.ts
- src/plugins/quarterOfYear/index.ts
add comments to:
- head of file for plugin QuarterOfYear
- function 'monthDiff'
- EsDay setters for date elements
> Pu: add comments to 3 files

- src/core/Impl/add.ts
make 'add' ignore unhandled units
> Fix: make 'add' ignore unhandled units

- docs/plugins/localizedFormat.md
- src/plugins/localizedFormat/index.ts
make localizedFormat run 'postFormat' from locale
> Fix: make localizedFormat run 'postFormat' from locale

- docs/index.md
- docs/plugins/isoWeek.md
- docs/plugins/quarterOfYear.md
- src/plugins/index.ts
- src/plugins/isoWeek/index.ts
- test/plugins/isoWeek.locales.test.ts
- test/plugins/isoWeek.test.ts
- test/plugins/isoWeek.utc.test.ts
Add plugin IsoWeek - this pr solves issue #78
> Feat: add plugin IsoWeek - solves issue #78

- src/plugins/advancedParse/index.ts
Make code a little bit better to read and understand.
The plugin still uses `this['$d'] = ....`
> Refactor: simplify code where possible

- src/plugins/dayOfYear/index.ts
+ replace name of parameter `d` with 'dayFactory'
+ replace magic number '864e5' with a constant named `SECONDS_A_DAY` (plus another division by 1000
> Refactor: beautify plugin DayOfYear

- src/common/date-fields.ts
- src/common/units.ts
- src/core/EsDay.ts
- src/core/Impl/add.ts
- src/core/Impl/diff.ts
- src/plugins/quarterOfYear/index.ts
- src/plugins/utc/index.ts
- src/types/index.ts
- test/add.test.ts
- test/diff.test.ts
- test/getset.test.ts
- test/plugins/quarterOfYear.test.ts
- test/plugins/utc.test.ts
Fix some minor problems with plural units in core and plugin functions
> Fix: last pr concerning plural units creates some errors when using a plural unit

- dev/templates/template-plugin.md
- docs/index.md
- docs/plugins/objectSupport.md
- docs/plugins/quarterOfYear.md
- docs/plugins/week.md
- src/common/date-fields.ts
- src/common/units.ts
- src/core/EsDay.ts
- src/plugins/index.ts
- src/plugins/objectSupport/index.ts
- src/plugins/quarterOfYear/index.ts
- src/plugins/utc/index.ts
- src/plugins/week/index.ts
- src/types/core.ts
- test/plugins/objectSupport.test.ts
- test/plugins/objectSupport.utc.test.ts
- test/plugins/quarterOfYear.test.ts
- test/plugins/utc.test.ts
- test/plugins/week.ar.test.ts
- test/plugins/week.de.test.ts
- test/plugins/week.en.test.ts
- test/plugins/week.utc.test.ts
> Feat: add plugin ObjectSupport

- tsconfig.json
- tsup.config.ts
Update ECMAscript target version to ES2020 - solves issue #113
> Chore: update ECMAscript target version to ES2020 - solves issue #113

- docs/core/get.md
- docs/core/set.md
- docs/index.md
- test/getset.test.ts
- add documentation for get and set
- refactor tests for get/set to use expectSameResult and expectSame
> Docs: add documentation for get and set

- scripts/gh-pages/create-gh-pages.js
> fix: remove unnecessary awat for a synchronous function

- docs/plugins/locale.md
- src/plugins/index.ts
- src/plugins/locale/index.ts
- src/plugins/locale/types.ts
- src/plugins/localizedParse/index.ts
- src/plugins/week/index.ts
- test/plugins/locale.test.ts
'getLocale' was a public method; changed it to be a method of esday.
Make 'setLocaleProperty' a public method.
> Feat: make 'getLocale' a method of esday

- README.md
Add link to documentation web site in github pages to readme.md file.
> Docs: add link to documentation web site to readme.md

- .github/workflows/coverage.yml
- .github/workflows/test-node.yaml
- src/core/EsDay.ts
- src/core/Impl/diff.ts
- src/core/Impl/format.ts
- src/plugins/advancedParse/index.ts
- src/plugins/localizedFormat/index.ts
- test/plugins/localizedFormat.test.ts
- vitest.config.ts
1st step to add a step to github ci pipeline that ensures that a pr does not reduce test coverage below 95%.
Additionally the code was optimized so that the untestable branches were removed.
This is the 1st of 2 steps; the new 'coverage.yml' file must already exist, before step 2 ist acceppted.
I could not test the final step (add the coverage report to the new created pull request).
> Chore: add check for minimal coverage to ci pipeline - step 1

- docs/core/get.md
- docs/core/set.md
- docs/plugins/index.md
- docs/plugins/pluralGetSet.md
- src/plugins/index.ts
- src/plugins/pluralGetSet/index.ts
- src/plugins/quarterOfYear/index.ts
- test/getset.test.ts
- test/plugins/isoWeek.test.ts
- test/plugins/pluralGetSet.test.ts
- test/plugins/quarterOfYear.test.ts
- test/plugins/week.en.test.ts
- vitest.config.ts
Add plugin plurals to core getter and setter
> Pu: add plugin plurals to core getter and setter

- docs/core/add.md
- docs/core/compare.md
- docs/core/format.md
- docs/core/get.md
- docs/core/index.md
- docs/core/parse.md
- docs/core/set.md
- docs/core/startOf.md
- scripts/gh-pages/create-gh-pages.js
> Docs: add documentation for more core methods

- dev/templates/template-plugin.md
- docs/plugins/index.md
- docs/plugins/localeData.md
- docs/plugins/localizedParse.md
- docs/plugins/relativeTime.md
- src/locales/lt.ts
- src/locales/zh.ts
- src/plugins/index.ts
- src/plugins/locale/index.ts
- src/plugins/locale/types.ts
- src/plugins/localeData/index.ts
- src/plugins/localeData/types.ts
- test/locales/lt.test.ts
- test/locales/zh.test.ts
- test/plugins/calendar.test.ts
- test/plugins/localeData.test.ts
- test/plugins/relativeTime.extend.test.ts
- test/plugins/relativeTime.test.ts
- test/plugins/week.en.test.ts
- test/plugins/week.test.ts
- test/util.ts
> Pu: add plugin locale data - solves issue #132

- .github/workflows/test-node.yaml
- src/plugins/utc/index.ts
- test/plugins/isoWeek.locales.test.ts
- test/plugins/isoWeek.utc.test.ts
- test/plugins/localeData.test.ts
- test/plugins/localizedFormat.test.ts
- test/plugins/localizedParse.test.ts
- test/plugins/localizedParse.utc.test.ts
- test/plugins/utc.plain.test.ts
- test/plugins/utc.test.ts
- test/plugins/week.utc.test.ts
This pr adds add and subtract methods to utc plugin to fix errors thrown when manipulating utc dates
> fix add / subtract for utc date value - fixes issue #137

- docs/plugins/objectSupport.md
- docs/plugins/relativeTime.md
- src/plugins/relativeTime/index.ts
- test/plugins/relativeTime.customize.test.ts
- test/plugins/relativeTime.extend.test.ts
- test/util.ts
Add missing functions to RelativeTime plugin
> Pu: add methods to relativeTime plugin to get or set the thresholds and the rounding function used
