g-mero/esday

package.json

Adding fields repository, bugs and homepage to package.json creates e.g. a reference to github in the npmjs package

Add fields repository, bugs and homepage to package.json

---

.commitlintrc.json
.husky/commit-msg
package.json

Add a script to prepare everything for a release:
+ bump version
+ create / update changelog file based on the commit messages.
The commit messages must follow some rules:
`<type>: <commit-message-less-than-120-chars>`
Optionally there can be a body and / or a footeer
```
<type>: <commit-message-less-than-120-chars>
<body line(s)
<footer line>
```
or
```
<type>: <commit-message-less-than-120-chars>
<footer line(s)>
```
The footer is used to signal breaking changes; this way the major version number of the package is increased. An example could be:
`BREAKING CHANGE: what resulted in a breaking change`
Using husky to automatically lint commit messages to make sure that the message has the required format.
For more details about the required format of the commit message see: …

Add script to prepare a release (bump version, create changelog)

---

eslint.config.mjs
src/core/Impl/startOf.ts
src/core/constant.ts
src/core/factory.ts
src/locales/en.ts
src/locales/zh.ts
src/plugins/locale/index.ts
src/types/core.ts
src/types/date.ts
src/types/index.ts
src/types/unit.ts
test/plugins/locale.test.ts
test/startOf.test.ts
tsup.config.ts

- `esday.locale(name:string)` to set global default locale.
- `esday.registerLocale(locale:Locale,rename?:string)` to register a locale.
- `esday().locale(name:string)` to use locale in a specific instance.

add plugin locale to support locale

---

package.json
src/core/utils.ts

Replace isArray function from the radash package with the standard javascript Array.isArray method

Refactor: replace isArray from radash with javascript Array method

---

src/plugins/customParseFormat/index.ts
tsconfig.json

Refactor: remove unnecessary ".ts" extension in path definition for esday in tsconfig.json
Refactor: use "import xxx from 'esday' wherever it is possible to improve consistency of imports

A minimal change: refactore imports to use 'esday' where possible

---

src/common/constants.ts
src/plugins/locale/index.ts
src/plugins/weekOfYear/index.ts
src/plugins/weekYear/index.ts
test/plugins/weekOfYear.test.ts
test/plugins/weekYear.test.ts

- default start week of a year should contain Thursday (ISO 8601)

feat: add plugin `weekOfYear` and `weekYear`

---

scripts/skipCI.cjs
test/plugins/isLeapYear.test.ts
test/plugins/isSameOrAfter.test.ts
test/plugins/isSameOrBefore.test.ts
test/plugins/minMax.test.ts
test/plugins/toArray.test.ts
test/plugins/toObject.test.ts
vitest.config.ts

Using 'it.each' generates a log entry for each entry in the array. Therefore we get a detailed log for a failing test, showing exactly which entry was the 'culprit'. And you can start a debug run for exactly 1 entry in the array.
On the other side, using forEach shows only 1 failing test and you have to find out, which value failed.

Refactor: replace forEach in tests with it.each

---

README.md

Dayjs and moment return different results, when using  toISOString() on an invalid date, To avoid ugly type castings or `if (x !== null)` assertions, we stay with the dayjs way of handling this case.

Docs: add remark on toISOString to readme

---

.github/workflows/lint.yaml
.github/workflows/test-macos.yaml
.github/workflows/test-node.yaml
.github/workflows/test-windows.yaml
scripts/skipCI.cjs
src/common/date-fields.ts
src/core/EsDay.ts
src/core/Impl/parse.ts
src/plugins/utc/index.ts
test/getset.test.ts
tsup.config.ts

The implementation of the parse method in the core module depends on the knowledge that there is an utc plugin (when creating a Date object from year, month etc.):
```
if (utc) {
return new Date(Date.UTC(Y, M, D, h, m, s, ms))
}
return new Date(Y, M, D, h, m, s, ms)
```
As the AdvancedParse plugin replaces the implementation of the parse method, this if statement would have to be duplicated to this plugin.
I refactored the code, to remove this dependency by creating a `dateFromDateComponents` method in the core module that is overwritten in the utc plugin. This way in 'standard' mode a Date with the current offset is created, while in 'utc' mode we will get an utc Date.
As an added bonus the utc plugin does not have to overwrite the parse method of the core module, potentially creating …

Refactor core module and utc plugin to remove tight coupling between plugins (utc, advancedParse)

---

package.json
src/core/factory.ts
src/plugins/locale/index.ts
src/plugins/locale/types.ts
test/plugins/locale.test.ts

Add a getter for the global locale to improve the compatibility with momentjs.
Syntax: `esday.locale()`.

feat: add a getter for the name of the global locale

---

src/plugins/locale/index.ts
src/plugins/locale/types.ts
src/plugins/weekOfYear/index.ts
test/plugins/locale.test.ts
test/plugins/weekOfYear.test.ts

Add a getter for the locale name of an instance (`esday().locale()`).
Add a getter for the locale object used by an esday object (`esday().localeObject`).
localeObject() is required by plugins that depend on the current locale of esday.

feat: add getter for locale of an instance; add getter localeObject

---

docs/core/diff.md
docs/index.md
src/common/constants.ts
src/common/date-fields.ts
src/common/units.ts
src/core/EsDay.ts
src/core/Impl/diff.ts
src/core/Impl/startOf.ts
test/diff.test.ts

Add method 'diff' to EsDay to calculate the difference between 2 dates based on the given units. This method is required e.g. to fix the errors in the WeekOfÝear plugin.

Feat: add method 'diff' to EsDay

---

docs/core/format.md
docs/index.md
docs/plugins/advancedFormat.md
src/common/constants.ts
src/common/str-utils.ts
src/core/Impl/format.ts
src/core/factory.ts
src/plugins/advancedFormat/index.ts
src/plugins/index.ts
src/types/core.ts
test/conversion.test.ts
test/diff.test.ts
test/format.test.ts
test/plugins/advancedFormat.test.ts
test/plugins/utc.test.ts

Redistributed parsing tokens.
As now it is very easy to add a formatting token in a plugin, I supposed that we add formatting tokens in the corresponding plugins (e.g. QuarterOfYear) and do not make AdvancedFormat require those plugins.

Feat: add plugin AdvancedFormat - solves issue #54

---

README.md
package.json
src/core/EsDay.ts
src/core/Impl/startOf.ts
src/plugins/locale/index.ts
test/add.test.ts
test/getset.test.ts
test/plugins/weekOfYear.ar.test.ts
test/plugins/weekOfYear.de.test.ts
test/plugins/weekOfYear.en.test.ts
test/startOf.test.ts

Make esday compatible with momentjs (version > 2.1):
when changing the month and the new month does not have enough days to keep the current day of month, esday behaves like momentjs and clamps to the end of the target month

Feat: make month setter compatible with current momentjs

---

src/plugins/dayOfYear/index.ts
src/plugins/locale/index.ts
src/plugins/locale/types.ts
src/plugins/quarterOfYear/index.ts
src/plugins/utc/index.ts
src/plugins/week/index.ts
test/plugins/utc.test.ts

The structure of the getter/setter overloads in the plugins was quite inhomogeneous.
To give the library a consistent style, I changed all occurrences to a consistent style following this example:
```
declare module 'esday' {
interface EsDay {
quarter(): number
quarter(quarterNumber: number): EsDay
}
}
// @ts-expect-error function is compatible with its overload
proto.quarter = function (quarterNumber?: number) {
if (quarterNumber === undefined) {
// Getter
return Math.ceil((this.month() + 1) / 3)
}
// Setter
return this.month((this.month() % 3) + (quarterNumber - 1) * 3)
}
```

Refactor: make all overload signatures for getter/setter follow the same pattern

---

src/core/EsDay.ts
src/plugins/utc/index.ts
test/plugins/advancedParse.test.ts

parsing day-of-month-only now returns current month (as moment.ja)

Fix: parsing day-of-month-only now returns current month

---

docs/plugins/advancedParse.md
src/plugins/advancedParse/index.ts

These changes to the advancedParse plugin are required by the isoWeek plugin:
- do not ignore results of postParseHandlers
- make parse handle missing format
- make parse keep existing parseOptions

Fix: some minor effects in advancedParse plugin

---

docs/plugins/localizedParse.md
src/plugins/localizedFormat/index.ts
src/plugins/localizedParse/index.ts

These changes to the localizedParse plugin are required by the isoWeek plugin:
- make localizedFormat run 'postFormat' from locale
- remove unnecessary types
- rename function parameter 'options' to 'parseOptions'
- make LocalizedParse use default locale 'en', if plugin locale is not loaded

Fix: some minor effects in localizedParse plugin

---

src/plugins/index.ts
src/plugins/relativeTime/index.ts
test/plugins/relativeTime.test.ts

There's a difference between Dayjs and Moment observed during testing: Dayjs doesn’t validate whether the date is valid. When given an invalid date, it always returns 'a month ago', whereas Moment returns 'Invalid date'.
Currently, we return 'Invalid Date' (C.INVALID_DATE_STRING). Was it intentional not to use 'Invalid date' instead? I don't quite remember.

feat: add plugin relativeTime

---

README.md
dev/templates/template-locale.ts
docs/index.md
src/common/constants.ts
test/format.test.ts
test/plugins/relativeTime.test.ts

Make 'Invalid date' identical to moment.js; dayjs uses 'Invalid Date', but this is grammatically wrong or references a Date object (which IMHO does not really make sense in most cases).

Fix: adapt string 'Invalid date' to moment.js

---

src/plugins/advancedParse/index.ts
src/plugins/advancedParse/types.ts
src/plugins/isoWeek/index.ts
src/plugins/localizedParse/index.ts
src/plugins/week/index.ts
test/plugins/localizedParse.utc.test.ts

Remove dependency from utc from the  plugins week, isoWeek and localizedParse.

Refactor: simplify method postParse in plugins week, isoWeek and localizedParse

---

src/core/EsDay.ts

Just for consistency in the code base: use `structuredClone()` for a deep copy in `Esday.clone()`

Rrefactor: use structuredClone for a deep copy in Esday.clone()

---

src/plugins/isoWeek/index.ts
src/plugins/localizedParse/index.ts
src/plugins/week/index.ts

Minimal change:  
use `createInstanceFromExist(d, this)` instead of `dayFactory(d, { utc: this['conf].utc })`.
This change makes code shorter and easier to read.

refactor: use 'createInstanceFromExist' instead of 'dayFactory'

---

docs/core/diff.md
test/diff.test.ts

Add more tests to diff.test.ts for short, long and plural units.
Update documentation to show all usable units.

Test: add tests for short and plural units in diff method

---

src/core/EsDay.ts
src/core/Impl/parse.ts
test/plugins/utc.test.ts

Add array of date components (year, month, day,...) to esday.utc(input).

feat: add array input to esday.utc()

---

src/plugins/index.ts
src/plugins/locale/index.ts
test/plugins/locale.test.ts
test/plugins/localizedFormat.test.ts

In the new function `updateLocale` here has been no test for the case that a locale does not exist.
Getting a locale will always return a Locale object; if the requested locale does not exist, esday (as momentjs) returns the default Locale.
Therefore the part of `updateLocale` that would throw an exception (what we do nowhere else in esday), will never be reached (and can therefore not be tested :-).
Fixed that minor point and added more tests for `updateLocale`.

fix: remove inaccessible part of updateLocale function

---

.github/workflows/coverage.yml
.github/workflows/test-node.yaml

Add the 2nd step to github ci pipeline that ensures that a pr does not reduce test coverage below 95%.
Together with "step 1" it should add a comment to a newly created pull request that shows the coverage of the project and the changes caused by this pull request - example:
PS: I could not test the final step (add the coverage report to the new created pull request).

Chore: add check for minimal coverage to ci pipeline to solve issue #120 - step 2
